run:
  timeout: 5m
  go: '1.23'

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: gh-actions-tui

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - typecheck
    - unused

issues:
  exclude-use-default: false
  exclude:
    - 'exported .* should have comment or be unexported'
    - 'should have a package comment'