name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build for current platform
        run: go build -v -ldflags="-X main.version=test -X main.commit=$(git rev-parse HEAD) -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o gh-actions-tui .

      - name: Test binary
        run: ./gh-actions-tui --version

      - name: Test GoReleaser config (dry run)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: check